#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  #Database connection
#  datasource:
#    url: jdbc:mysql://localhost:3306/ecom-notification
#    username: root
#    password: password
#  #Email Configuration
#  mail:
#    host: smtp.gmail.com
#    username: anhlee.beta@gmail.com
#    password: erkhiicsfxluijij
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#constant:
#  url:
#    user-service: "http://localhost:8000"