build:
  version: 1.0.0
server:
  port: 8004
spring:
  application:
    name: notification
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  #Database connection
  datasource:
    url: jdbc:mysql://localhost:3306/ecom-notification
    username: root
    password: password
  #Email Configuration
  mail:
    host: smtp.gmail.com
    username: anhlee.beta@gmail.com
    password: erkhiicsfxluijij
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    #Kafka
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

# Constants
constant:
  kafka:
    topic:
      payment-event: payment-event
    group-id: notification-service
  url:
    user-service: http://localhost:8000
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#----------------------------------------------------------------
#DATABASE
#spring.datasource.url=jdbc:mysql://localhost:3306/ecom-notification
#spring.datasource.username=root
#spring.datasource.password=password
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql=true
##EMAIL
#spring.mail.host=smtp.gmail.com
#spring.mail.username=anhlee.beta@gmail.com
#spring.mail.password=erkhiicsfxluijij
#spring.mail.port=587
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
##KAFKA
#spring.kafka.bootstrap-servers= localhost:29092
##spring.kafka.producer.value-serializer= org.springframework.kafka.support.serializer.JsonSerializer
##spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
#server.port=8004
##CONSTANTS
#constant.kafka.topic.payment-event=payment-event
#constant.kafka.group-id=notification-service
#constant.url.user-service=http://localhost:8000
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka